const riddles = [
  { question: "What has a head and a tail, but no body?", answer: "Coin" },
  { question: "You cannot keep me until you have given me. What am I?", answer: "Your word" },
  { question: "I am not alive, but I grow; I don’t have lungs, but I need air; I don’t have a mouth, but water kills me. What am I?", answer: "Fire" },
  { question: "What is easy to get into but hard to get out of?", answer: "Trouble" },
  { question: "There’s only one word in the dictionary that’s spelled wrong. What is it?", answer: "Wrong" },
  { question: "Thousands lay up gold within this house, but no man-made it. Spears past counting guard this house, but no man wards it.", answer: "Beehive" },
  { question: "What begins with T ends with T and has T in it?", answer: "A teapot" },
  { question: "What has a neck but no head?", answer: "A bottle" },
  { question: "What is full of holes but still holds water?", answer: "A sponge" },
  { question: "What is always in front of you but can’t be seen?", answer: "The future" },
  { question: "What is next in this sequence? JFMAMJJASON", answer: "The letter D. The sequence contains the first letter of each month." },
  { question: "I’m as hard as a rock, but I melt immediately in hot water. What am I?", answer: "An ice cube" },
  { question: "How do you make the number one disappear by adding to it?", answer: "Add the letter ‘G’ and it becomes Gone" },
  { question: "How much dirt is in a hole that measures 2 feet by 3 feet by 4 feet?", answer: "None" },
  { question: "I’m tall when I’m young, I’m short when I’m old. What am I?", answer: "Candle / Pencil" },
  { question: "A man who was outside in the rain without an umbrella or hat didn’t get a single hair on his head wet. Why?", answer: "He was bald." },
  { question: "What is full of holes but still holds water?", answer: "A sponge" },
    { question: "If you don’t keep me, I’ll break. What am I?", answer: "A promise" },
    { question: "What two words, added together, contain the most letters?", answer: "Post office" },
    { question: "Which word becomes shorter when you add 2 letters to it?", answer: "Short" },
    { question: "What’s worth more after it’s broken?", answer: "An egg" },
    { question: "Ready for the tough questions? Try these Really Hard Riddles." },
    { question: "Why did Snap, Crackle, and Pop get scared?", answer: "They heard there was a cereal killer on the loose." },
    { question: "What can go up a chimney down, but can’t go down a chimney up?", answer: "An umbrella. If your umbrella is down, it can fit through a chimney, but if it’s up, it won’t fit!" },
    { question: "How do you spell COW in thirteen letters?", answer: "SEE O DOUBLE YOU." },
    { question: "Why is an island like the letter T?", answer: "They’re both in the middle of water!" },
    { question: "What has wheels and flies, but it is not an aircraft?", answer: "A garbage truck." },
    { question: "What tastes better than it smells?", answer: "Tongue" },
    { question: "What do you call a bear without ears?", answer: "B" },
    { question: "Who lives an exhausting life?", answer: "The exhaust." },
    { question: "What hard rock group has four dudes, but not one of them plays the guitar?", answer: "Mount Rushmore." },
    { question: "Sometimes I am born in silence, Other times, no. I am unseen, But I make my presence known. In time, I fade without a trace. I harm no one, but I am unpopular with all. What am I?", answer: "A fart" },
    { question: "What do you get if you cross poison ivy with a four-leaf clover?", answer: "A rash of good luck!" },
    { question: "Why is Europe like a frying pan?", answer: "Because it has Greece at the bottom." },
    { question: "What do you call a fly without wings?", answer: "A walk" },
    { question: "What word has five letters but sounds like it only has one?", answer: "Queue" },
    { question: "I am neither a guest nor a trespasser be, to this place I belong, it belongs also to me.", answer: "Home" },
    { question: "What is 3/7 chicken, 2/3 cat, and 2/4 goat?", answer: "Chicago!" },
    { question: "A pet shop owner had a parrot with a sign on its cage that said Parrot repeats everything it hears. Davey bought the parrot and for two weeks he spoke to it and it didn’t say a word. He returned the parrot but the shopkeeper said he never lied about the parrot. How can this be?", answer: "The parrot was deaf." },
    { question: "Which part of a road do ghosts most love to travel?", answer: "The dead end" },
    { question: "Why can’t a pirate ever finish the alphabet?", answer: "Because he always gets lost at sea!" },
    { question: "What do Alexander The Great and Winnie The Pooh have in common?", answer: "Same middle name." },
    { question: "Two Fathers and Two Sons Riddle", answer: "Two fathers and two sons sat down to eat eggs for breakfast. They ate exactly three eggs, each person had an egg. The riddle is for you to explain how." },
    { question: "Add me to myself and multiply by 4. Divide me by 8 and you will have me once more. What number am I?", answer: "Any number." },
    { question: "In a certain country ½ of 5 = 3. If the same proportion holds, what is the value of 1/3 of 10?", answer: "4" },
    { question: "If a zookeeper had 100 pairs of animals in her zoo, and two pairs of babies are born for each one of the original animals, then (sadly) 23 animals don’t survive, how many animals do you have left in total?", answer: "977 animals (100 x 2 = 200; 200 + 800 = 1000; 1000 – 23 = 977)" },
    { question: "There is a 3-digit number. The second digit is four times as big as the third digit, while the first digit is three less than the second digit. What is the number?", answer: "141" },
    { question: "Ram has 5 sons. Each of his sons has a sister. How many children does Ram have?", answer: "Six. All of the sons have the same sister." },
    { question: "100 coins were dropped and got scattered inside a dark place. 90 of the coins fell with heads facing up and the remaining 10 coins fell with tails up. You are asked to sort the coins into 2 piles. Each pile should have the same count of tails-up coins. How is it possible?", answer: "Make 2 piles, one with 90 coins and the other with 10 coins. Flip 10 coins on the pile of 90. The piles will have the same count of tails-up coins." },
    { question: "A merchant can place 8 large boxes or 10 small boxes into a carton for shipping. In one shipment, he sent a total of 96 boxes. If there are more large boxes than small boxes, how many cartons did he ship?", answer: "11 cartons total" },
    { question: "In an alien land far away, half of 10 is 6. If the same proportion holds true, then what is 1/6th of 30 in this alien land?", answer: "6" },
    { question: "What is half of two plus two?", answer: "three" },
    { question: "What do geometry teachers have decorating their floor?", answer: "Area rugs!" },
    { question: "You have 50 biscuits. How many times can you subtract 5 from 50 biscuits?", answer: "Once only because after that it will not be 50 biscuits. As you subtract 5 biscuits it will be 45 and not 50 anymore." },
    { question: "I saw my math teacher with a piece of graph paper yesterday", answer: "I think he must be plotting something." },
    { question: "The price of a duck is Rs. 9, a spider costs Rs. 36 and a bee was priced Rs. 27. By taking into account this information, what will be the price of a cat?", answer: "Rs.18 (Rs. 4.50 per leg)" },
    { question: "Suppose 1+9+8=1, then what can be 2+8+9?", answer: "10! (Consider the first letter of the spelling of each digit, One+Nine+Eight= ONE, similarly Two+Eight+Nine= TEN)" },
    { question: "Mrs. Jones was very proud of her apple tree. One autumn, after harvesting her apples, she called her 3 sons together. “Here are 150 apples,” she said. I want you to take them to the market tomorrow and sell them for me. She gave Paul 15 apples, Nick 50, and Ben 85. “Your job,” added Mrs. Jones, “is to sell the apples in such a way that each of you brings home the same amount of money.” How do they do it?", answer: "The first buyer purchases 12 dozen apples at $1 per dozen. Paul sells him one dozen and has three apples left; Nick sells him four-dozen and has two apples left, and Ben sells him seven-dozen and has one apple left. Then, a second buyer comes along and buys all their remaining apples for $3 a piece. The 3 brothers head home with $10 each." },
    { question: "If 9999 = 4, 8888 = 8, 1816 = 6, 1212 = 0, then 1919 =", answer: "4" },
    { question: "Why was math class so long?", answer: "The teacher kept going off on a tangent." },
    { question: "If you multiply this number by any other number, the answer will always be the same. What number is this?", answer: "Zero" },
    { question: "There are 100 pairs of dogs in a zoo. Two pairs of babies are born for every dog. Unfortunately, 23 of the dogs have not survived. How many dogs would be left in total?", answer: "977 dogs" },
    { question: "What do you answer even though it never asks you questions?", answer: "A doorbell or a phone" },
    { question: "What word describes a woman who does not have all her fingers on one hand?", answer: "Typical. She would not be so if she had 10 fingers on one hand." },
    { question: "First, think of the person who lives in disguise, who deals in secrets and tells naught but lies. Next, tell me what’s always the last thing to mend, the middle of the middle and the end of the end? Finally, give me the sound often heard during the search for a hard-to-find word. Now, string them together, and answer me this: Which creature would you be unwilling to kiss?", answer: "A spider" },
    { question: "Mr. and Mrs. Mustard have 6 daughters and each daughter has one brother. How many people are in the Mustard family?", answer: "There are 9 Mustards in the family. Since each daughter shares the same brother, there are 6 girls, 1 boy, and Mr. and Mrs. Mustard." },
    { question: "What word in the English language does the following: the first two letters signify a male, the first three letters signify a female, the first four letters signify a great, while the entire world signifies a great woman. What is the word?", answer: "Heroine" },
    { question: "How can you drop a raw egg from a height onto a concrete floor without cracking it?", answer: "Concrete floors are very hard to crack." },
    { question: "Strip the skin under my skin, and my flesh you’ll reveal. It tastes sweet and tart, now throw out the peel. What is it?", answer: "Orange" },
    { question: "Which of the following is the largest? Triangle, circle, square, or rectangle?", answer: "Rectangle, it has the most letters" },
    { question: "What building has the most stories?", answer: "A library" },
    { question: "Pronounced as 1 letter, And written with 3, 2 letters there are, and 2 only in me. I’m double, I’m single, I’m black blue, and grey, I’m read from both ends, and the same either way. What am I?", answer: "Eye" },
    { question: "Sometimes I shine, sometimes I’m dull, sometimes I am big, and sometimes I am small. I can be pointy, I can be curved, and don’t ask me questions because even though I’m sharp, I’m not smart enough to answer you. What am I?", answer: "A knife" },
    { question: "It was an especially hot day and a man was walking in the desert. In the distance, the man suddenly saw a restaurant. He rejoiced, ran to it, and immediately asked the waiter for a glass of water. Instead, the waiter pulled out a gun and pointed it at the man’s head. The man replied with, “thank you.” Why did the man thank the waiter?", answer: "It was a water gun!" },
    { question: "Who has married many women but was never married?", answer: "The priest" },
    { question: "I come from a mine and get surrounded by wood always. Everyone uses me. What am I?", answer: "Pencil lead" },
    { question: "I am believed to be one-dimensional, and tinier than anything can be. Many say I’m the basis of all that we see. What am I?", answer: "A string" },
    { question: "Break it and it gets better; set it and it’s harder to break.", answer: "Record" },
    { question: "Forward, I am heavy; backward, I am not. What am I?", answer: "A ton" },
    { question: "You measure my life in hours and I serve you by expiring. I’m quick when I’m thin and slow when I’m fat. The wind is my enemy.", answer: "A candle" },
    { question: "If you are running a race, and you pass the person in second, what place are you in?", answer: "Second place" },
    { question: "The cock crew, the sky was blue, and the bells in heaven were striking 11. ‘Tis time for this poor soul To go to heaven. What am I?", answer: "The fox burying his grandmother under a hollybush." },
    { question: "A doctor and a bus driver are both in love with the same woman, an attractive girl named Sarah. The bus driver had to go on a long bus trip that would last a week. Before he left, he gave Sarah seven apples. Why?", answer: "An apple a day keeps the doctor away!" },
    { question: "You have me today, Tomorrow you’ll have more; As your time passes, I’m not easy to store; I don’t take up space, But I’m only in one place; I am what you saw, But not what you see. What am I?", answer: "Memories" },
    { question: "If two snakes marry, what will their towels say?", answer: "Hiss and hers" },
    { question: "On Christmas Eve, when Santa leaves his workshop at the North Pole, what direction does he travel?", answer: "South. The only way to travel from the North Pole is south." },
    { question: "What four-letter word ends in it and can be found at the bottom of birdcages?", answer: "Grit" },
    { question: "People make me, save me, change me, raise me. What am I?", answer: "Money" },
    { question: "If someone is packing heat what are they carrying?", answer: "A gun." },
    { question: "Four cars come to a four-way stop, each coming from a different direction. They can’t decide who got there first, so they all go forward at the same time. All 4 cars go, but none crash into each other. How is this possible?", answer: "They all made right-hand turns." },
    { question: "With pointed fangs, I sit and wait. With piercing force, I crunch out fate. Grabbing victims, proclaiming might, physically joining with a single bite. What am I?", answer: "A stapler" },
    { question: "When does Christmas come before Thanksgiving?", answer: "In the dictionary." },
    { question: "A drunk man comes home and finds his wife in bed with another man. He goes and grabs his gun out of the closet! What was opened first?", answer: "A bottle." },
    { question: "If the end of the year is on December 31st, what is the end of Christmas?", answer: "The letter ‘s.’ It’s the last letter in Christmas, so it’s obviously the end!" },
    { question: "What does a man do only once in his lifetime, but women do once a year after they are 29?", answer: "Turn 30" },
    { question: "What did the smelly feet and smelly shoes say to each other before going on a long day of walking?", answer: "This socks!" },
    { question: "I have a head like a cat and feet like a cat, but I am not a cat. What am I?", answer: "A kitten" },
    { question: "I have no life, but I can die. What am I?", answer: "A battery" },
    { question: "What do you call it when your parachute doesn’t open?", answer: "Jumping to a conclusion" },
    { question: "What do you call a grandfather clock?", answer: "An old-timer" },
    { question: "There’s a one-story house where everything is yellow. The walls are yellow. The doors are yellow. Even all the furniture is yellow. The house has yellow beds and yellow couches. What color are the stairs?", answer: "There aren’t any stairs—it’s a one-story house." },
    { question: "What begins with an E but only has one letter in it?", answer: "An envelope" },
    { question: "What belongs to you but is used most often by everyone else?", answer: "Your name" },
    { question: "You cannot come in or go out without me. What am I?", answer: "A door" },
    { question: "I am hard like stone, but I grow on your body. What am I?", answer: "A tooth" },
    { question: "What room doesn’t have any windows?", answer: "A mushroom" },
    { question: "If you throw a blue stone into the Red Sea, what will it become?", answer: "Wet" },
    { question: "I’m a single-digit number having no value. Which number am I?", answer: "Zero" },
    { question: "What goes up and down the stairs without moving?", answer: "A carpet" },
    { question: "What goes around and around the wood but never goes into the wood?", answer: "The bark of a tree" },
    { question: "A man was driving a black truck. His lights were not on. The moon was not out. A lady was crossing the street. How did the man see her?", answer: "It was a bright, sunny day." },
    { question: "What has legs but cannot walk?", answer: "A chair" },
    { question: "What word is spelled wrong in every dictionary?", answer: "Wrong" },
    { question: "Tom’s father has three sons: Jim, John, and what’s the third one’s name?", answer: "Tom" },
    { question: "To you, rude would I never be, though I flag my tongue for all to see. What am I?", answer: "A dog" },
    { question: "Which one of Santa’s reindeer is the fastest?", answer: "Dasher" },
    { question: "I like food, but water kills me. What am I?", answer: "Fire" },
    { question: "I shrink smaller every time I take a bath. What am I?", answer: "Soap" },
    { question: "What tastes better than it smells?", answer: "A tongue" },
    { question: "A precious stone, as clear as diamond. Seek it out while the sun’s near the horizon. Though you can walk on water with its power, try to keep it, and it’ll vanish in an hour.", answer: "Ice" },
    { question: "What cruel person would sit on a baby?", answer: "Babysitter" },
    { question: "A weighty currency.", answer: "Pound" },
    { question: "I can come in many colors Like red, yellow, orange, blue or green When you put my lead on paper Your drawings or writing can be seen", answer: "Pencil" },
    { question: "A bridge in a hollow And a hundred going over it No blacksmith, nor mason, nor carpenter built it.", answer: "Frozen river" },
    { question: "Some are used for fabric And some are used for hair Some are used for paper And one is called a pair", answer: "Scissors" },
    { question: "I am always running, but never get tired or hot. What am I?", answer: "The refrigerator" },
    { question: "I come on a roll but I’m not toilet paper I’m often clear but I’m not a window I’m often put in a dispenser but I’m not handsoap I help you wrap a gift but I’m not a pair of scissors I have adhesive on one side but I’m not a postage stamp", answer: "Sticky tape" },
    { question: "How many bananas can you eat if your stomach is empty?", answer: "Just one after that it’s not empty anymore." },
    { question: "this vehicle makes frequent stops So getting to places can be slow In London they’re usually red The ones you take to school are yellow", answer: "Bus" },
    { question: "I wiggled and cannot see. I’m sometimes underground and sometimes on a tree. I really don’t want to be on a hook, and I become a person when combined with a book", answer: "Worm" },
    { question: "What falls often but never gets hurt?", answer: "Snow or rain" },
    { question: "I can travel at nearly 100 miles per hour, but never leave the room. You can cover me up, but that doesn’t slow me down. You will not know if I come only once or again and again and again. What am I?", answer: "A sneeze" },
    { question: "My love, when I gaze on thy beautiful face, Careering along, yet always in place — The thought has often come into my mind If I ever shall see thy glorious behind.", answer: "Moon" },
    { question: "I like to twirl my body but keep my head up high. After I go in, everything becomes tight. What am I?", answer: "Screw" },
    { question: "It cannot be seen, cannot be felt, Cannot be heard, cannot be smelt. It lies behind stars and under hills, And empty holes it fills. It comes first and follows after, Ends life, kills laughter.", answer: "Darkness" },
    { question: "First you see me in the grass dressed in yellow gay; next I am in dainty white, then I fly away. What am I?", answer: "Dandelion" },
    { question: "People have stepped on me, but not many. I never stay full for long. I have a dark side. What am I?", answer: "The moon" },
    { question: "How far can you walk into a forest?", answer: "One step. Then you’re walking through the forest." },
    { question: "Turn me on my side and I am everything. Cut me in half and I am nothing. What am I?", answer: "The number 8 on its side" },
    { question: "An old man dies, leaving behind two sons. In his will, he orders his sons to race with their horses, and the one with the slower horse will receive his inheritance. The two sons race, but since they’re both holding their horses back, they go to a wise man and ask him what they should do. The brothers race again, this time at full speed. What did the wise man tell them?", answer: "To switch horses." },
    { question: "Which two keys cannot open any doors?", answer: "Monkeys and donkeys" },
    { question: "I am associated with Spring. I love to hop in the grass. I play in your vegetable garden. My teeth are long and sharp. I am soft to pet.", answer: "Rabbit" },
    { question: "I am a word of letters three, add two and fewer there will be. What am I?", answer: "Few" },
    { question: "I am in the beginning of sorrow and sadness. You will also find me in happiness. You will find me in sun and stars, but not in moon. I am in summer and spring but not in fall or winter. Who am I?", answer: "The letter ‘s.’" },
    { question: "Which coat goes on best when wet", answer: "A coat of paints" },
    { question: "What is harder to catch the faster you run?", answer: "Icicle" },
    { question: "Can you name three consecutive days without using the words Monday, Tuesday, Wednesday, Thursday, Friday, Saturday, or Sunday?", answer: "Yesterday, Today, and Tomorrow." },
    { question: "What time of day, when written in capital letters, is the same forward, backward, and upside down?", answer: "Noon" },
    { question: "What seven-letter word becomes longer when the third letter is removed?", answer: "Lounger = Longer" },
    { question: "What 8 letter word can have a letter taken away and it still makes a word. Take another letter away and it still makes a word. Keep on doing that until you have one letter left. What is the word?", answer: "The word is starting! starting, staring, string, sting, sing, sin, in, I" },
    { question: "Which band never plays music?", answer: "A rubber band" },
    { question: "What is red and smells like paint?", answer: "A red paint" },
    { question: "What body part is pronounced as one letter, but written with three, only two different letters are used?", answer: "Eye" },
    { question: "A boy was at a carnival and went to a booth where a man said to the boy, “if I write your exact weight on this piece of paper, you have to give me $50, but if I cannot, I will pay you $50.” The boy looked around and saw no scale, so he agreed, thinking that no matter what was written, he could say more or less. In the end, the boy ended up paying the man $50. How did the man win the bet?", answer: "The man did exactly as he said he would and wrote ‘your exact weight’ on the paper." },
    { question: "What English word retains the same pronunciation, even after you take away four of its five letters?", answer: "Queue" },
    { question: "I am a kind of coat that can only be put on when wet. What am I?", answer: "Paint" },
    { question: "Why don’t lobsters share?", answer: "They’re shellfish!" }

];
  
  
  
  let currentRiddleIndex = -1;
  let timeout;
  
  function displayRiddle() {
    currentRiddleIndex = (currentRiddleIndex + 1) % riddles.length;
    const currentRiddle = riddles[currentRiddleIndex];
    document.getElementById('riddle').textContent = currentRiddle.question;
    document.getElementById('answer').textContent = currentRiddle.answer;
    document.getElementById('answer').style.display = 'none';
    clearTimeout(timeout);
    timeout = setTimeout(() => {
      document.getElementById('answer').style.display = 'block';
    }, 15000); // 15 seconds
  }
  
  document.addEventListener('DOMContentLoaded', () => {
    displayRiddle();
  
    document.addEventListener('click', () => {
     displayRiddle();
    });
  });